### ISSUE TITLE
Starting fresh cqrweblog

### ISSUE THREAD

**Issue by OH1KH** [dl8bh/cqrweblog#6]
Hi!
Long time since...
I am still using the version from 2015 and it works fine.
Today I cloned a fresh one and tried to install it to my laptop. No luck. (when doing by setup/readme.md I.E. just edit config.php)

It seems that if database "cqrlog_web" does not exist and it does not create it.
On the other hand I could not use my server's "cqrlog_web" as query refers to "settings.cqrlog_web" and that old one does not have "settings" table.

Have I forgotten something from setup procedure?

**Comment by dl8bh** [comment]
Hi Saku,
please try tag 0.9 version, I started working on the master recently. The 0.9 tag is the old version you know. Further details on the new version will follow

**Comment by OH1KH** [comment]
Yep!
reverted back to 0.9 tag and it works as expected.
I will be waiting the new version.
